name         'blentz-selinux_types'
version      '0.1.0'
source       'https://github.com/jgoldschrafe/puppet-selinux_types'
author       'Jeff Goldschrafe, Brett Lentz, Mirosław Nagaś'
license      'Public Domain'
summary      'SELinux types'
description  'Types for interacting with the SELinux database from Puppet'
project_page 'https://github.com/jgoldschrafe/puppet-selinux_types'
